---
- name: Install NIS
  apt:
    name: 'nis'
    state: 'present'
    update_cache: 'yes'

- name: Install /etc/yp.conf
  copy:
    src: "{{ ansible_role_nis_cfg_path }}"
    dest: "/etc/yp.conf"
    mode: 0644
    owner: 'root'
    group: 'root'
  when: ansible_role_nis_cfg_path is defined
  register: ansible_role_nis_cfg_installed

- name: Enable & (re)start NIS
  service:
    name: "{{ansible_role_nis_svc_name}}"
    state: 'restarted'
    enabled: 'yes'
  when: ansible_role_nis_cfg_installed.changed
