---
- name: Pre-set the nis domain
  shell: echo "nis nis/domain string {{ ansible_role_nis_domain }} Y" | debconf-set-selections

- name: Place defaultdomain file
  template:
    src: "defaultdomain.j2"
    dest: "/etc/defaultdomain"
    mode: 0644
    owner: 'root'
    group: 'root'

- name: Install NIS
  apt:
    name: 'nis'
    state: 'present'
    update_cache: 'yes'

- name: Install /etc/yp.conf
  copy:
    src: "{{ ansible_role_nis_cfg_path }}"
    dest: "/etc/yp.conf"
    mode: 0644
    owner: 'root'
    group: 'root'
  when: ansible_role_nis_cfg_path is defined
  register: ansible_role_nis_cfg_installed

- name: Add NIS group(s) to passwd
  lineinfile:
    path: /etc/passwd
    line: "{{ item }}"
  with_items: "{{ ansible_role_nis_groups | default([]) }}"

- name: Enable & (re)start NIS
  service:
    name: "{{ansible_role_nis_svc_name}}"
    state: 'restarted'
    enabled: 'yes'
  when: ansible_role_nis_cfg_installed.changed
